$(document).ready(function(){
    $('#submit-form').validate({
        rules:{
            fname:{
                required:true,
                minlength:3
            },
            lname:{
                required:true,
            },
            emailAddress:{
                required:true,
                email:true
            }
        }
    })
})